bootstrap.servers=kafka1.SCRAMBLE_COMPANY_BRAND_000002.internal:9092,kafka2.SCRAMBLE_COMPANY_BRAND_000003.internal:9092
schema.registry.url=SCRAMBLE_URL_000001
security.protocol=SASL_SSL
sasl.jaas.config=password=secret123
kafka.api.key=SCRAMBLE_API_KEY_000001
