oauth.client.id=SCRAMBLE_COMPANY_BRAND_000004-loan-client
oauth.client.secret=SCRAMBLE_SECRET_KEY_000001
oauth.token.url=SCRAMBLE_URL_000002
oauth.redirect=SCRAMBLE_URL_000003
oauth.jwt=SCRAMBLE_JWT_000001
oauth.admin=SCRAMBLE_EMAIL_000001
