bootstrap.servers=kafka1.B92470BC.internal:9092,kafka2.B92470BC.internal:9092
schema.registry.url=astra://lineastr.aline.ast/rali-nea/s6/tralin
security.protocol=SASL_SSL
sasl.jaas.config=password=falcon331
kafka.api.key=evermo2468024602REEVERMOREEV
