oauth.client.id=B92470BC-loan-client
oauth.client.secret=paral-laxpar
oauth.token.url=spect://rumspect.rumsp.ect/rums-pec/t2/rumsp/ectru
oauth.redirect=crest://fallcres.tfall.cre/stfallcr
oauth.jwt=veRteXonVeRTExO2NvErTeX6oNV1ErtEXON4.veR3t6ExOnverTExO0n8Vertex0oNVE2RtExoNveRt1.EXONVERTE0XONVE3579135913RTEXON
oauth.admin=meridian214@example.com
