# Secrets — SCRAMBLECLI test vectors
password=aerio791
password=falcon331
db.password=team331
api.key=evermo2468024602REEVERMOREEV
api_key=ste064208
client.secret=paral-laxpar
secret.key=bank-secret
jwt.token=haLcyOniXhALCyO2NiXhAlC6yON1IxhALCY4.onI3x6HaLcyonIXhA0lCyonix7hALC1YoNixHalCy8.ONIXHALCYONIXH9357913571ALCYON

password=aerio791  # occurrence 1
password=aerio791  # occurrence 2
password=aerio791  # occurrence 3
password=aerio791  # occurrence 4
password=aerio791  # occurrence 5
api.key=evermo2468024602REEVERMOREEV  # occurrence 1
api.key=evermo2468024602REEVERMOREEV  # occurrence 2
api.key=evermo2468024602REEVERMOREEV  # occurrence 3
api.key=evermo2468024602REEVERMOREEV  # occurrence 4
api.key=evermo2468024602REEVERMOREEV  # occurrence 5

-----ORBIT ALORBIT ALO-----
RBITaLORBITALorbitaL1o8RBITALORBITalorBiTaLORbITALOrbitaLorbItal
5555533333ORBITA5555533333LORBIT5555533333ALORBI5555533333TALORB
-----ITA LORBITA LOR-----

-----YARAY ARA YARAYAR AYA-----
RAYAraYARAYARAYArayarAyarAyarAyarayarAyarAyaRayarayarayArayAraYara
7935791357YARAYA7935791357RAYARA7935791357YARAYA7935791357RAYARA
8246802460YARAYA8246802460RAYARA8246802460YARAYA8246802460RAYARA
-----YAR AYA RAYARAY ARA-----
