bootstrap.servers=kafka1.icici.internal:9092,kafka2.icici.internal:9092
schema.registry.url=https://internal.icici.com/loan-api/v1/schema
security.protocol=SASL_SSL
sasl.jaas.config=password=secret123
kafka.api.key=abcdef1234567890SCRAMBLETEST
